#!/bin/bash

set -e

echo "🔵 Deploying BLUE version..."
kubectl apply -f blue_deployment.yaml

echo "🟢 Deploying GREEN version..."
kubectl apply -f green_deployment.yaml

echo "🔁 Applying shared Service..."
kubectl apply -f kubeservice.yaml

echo "🔍 Checking logs for GREEN pod..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs "$GREEN_POD"

echo "✅ Blue-Green deployment applied. Service currently points to: $(kubectl get service messaging-app-service -o=jsonpath='{.spec.selector.version}')"
